// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1p49wL2dnfCUtw6svsEGxq_VpjJ9diw0',
    appId: '1:503878880134:web:9b2e6200d4e3a236657a07',
    messagingSenderId: '503878880134',
    projectId: 'grindmode-4b219',
    authDomain: 'grindmode-4b219.firebaseapp.com',
    storageBucket: 'grindmode-4b219.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhg7W_gu61GLtN1Fud0ecNWZp2X9XGIvs',
    appId: '1:503878880134:android:82747f7d019eff96657a07',
    messagingSenderId: '503878880134',
    projectId: 'grindmode-4b219',
    storageBucket: 'grindmode-4b219.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1b55Y5A0U8Rt4mxuF64prLe02zX20kzU',
    appId: '1:503878880134:ios:ad8024b01ac316a5657a07',
    messagingSenderId: '503878880134',
    projectId: 'grindmode-4b219',
    storageBucket: 'grindmode-4b219.firebasestorage.app',
    iosBundleId: 'com.example.grindmode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1b55Y5A0U8Rt4mxuF64prLe02zX20kzU',
    appId: '1:503878880134:ios:ad8024b01ac316a5657a07',
    messagingSenderId: '503878880134',
    projectId: 'grindmode-4b219',
    storageBucket: 'grindmode-4b219.firebasestorage.app',
    iosBundleId: 'com.example.grindmode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1p49wL2dnfCUtw6svsEGxq_VpjJ9diw0',
    appId: '1:503878880134:web:d825f75ab5f16eee657a07',
    messagingSenderId: '503878880134',
    projectId: 'grindmode-4b219',
    authDomain: 'grindmode-4b219.firebaseapp.com',
    storageBucket: 'grindmode-4b219.firebasestorage.app',
  );
}
